version: "3.9"
services: 
  app:
    build: .
    container_name: swapp
    volumes: 
      - .:/go/src
    ports:
      - 8000:8000
    depends_on: 
      - mongodb
    links: 
      - mongodb
    networks: 
      - swapi
    
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks: 
      - swapi
    volumes:
      - swapidb:/data/db

volumes:
  swapidb:
networks: 
  swapi:
    driver: bridge